export const INIT_POWERUPS = { reveal: 0, double: 0, shield: 0 };
export const INIT_TIMED_CLEF_PROGRESS = {
  treble: { level3Clears: 0, diamondUnlocked: false, legendaryUnlocked: false },
  alto: { level3Clears: 0, diamondUnlocked: false, legendaryUnlocked: false },
  bass: { level3Clears: 0, diamondUnlocked: false, legendaryUnlocked: false },
};

export const INITIAL_STATE = {
  phase: "menu", clef: "treble",
  word: null, slots: [], slotIndex: 0, guessed: {}, highlights: {},
  streak: 0, score: 0, stageIndex: 0,
  butterflyCorrectCount: 0,
  butterflyPending: false,
  isButterfly: false, showConfetti: false,
  streakMilestone: null,
  message: "", usedWords: [], isDone: false, wrongCount: 0, slotWrongCount: 0,
  completed: 0, unlockedStages: [0], popup: null,
  arcadeScore: 0, arcadeOver: false, arcadeClef: null,
  arcadeWordDone: false,
  showLeaderboard: false, enteringName: false, arcadeInitials: "",
  arcadePool: null, arcadePractice: false,
  timedScore: 0, timedOver: false, timedWordDone: false,
  timedLevel: 0, timedLevelCorrect: 0,
  timedClefProgress: { ...INIT_TIMED_CLEF_PROGRESS },
  timedMode: "normal", timedUnlockedMode: null, timedBadgeUnlockedClef: null,
  transitioning: false,
  powerups: { ...INIT_POWERUPS },
  doubleActive: false,
  shieldActive: false,
  stats: {
    wordsCompleted: 0, correctGuesses: 0, totalGuesses: 0,
    bestStreak: 0, butterflies: 0, xp: 0, noteAttempts: {}, noteCorrect: {},
    legendaryBadges: { treble: false, alto: false, bass: false },
  },
  showStats: false,
  storyChapter: 0,
  storyComplete: false,
  storyWordDone: false,
  showStreakLB: false,
  streakLBEntering: false,
  streakInitials: "",
  lastBigStreak: 0,
  songIndex: 0,
  songNoteIndex: 0,
  songNotes: null,
  songDone: false,
  songCorrect: 0,
  songNoteWrongCount: 0,
  weakNotes: null,
  weakScore: 0,
  weakTotal: 0,
  scrambleWord: null,
  scrambleNotes: null,
  scrambleOrigOrder: null,
  scrambleGuessed: {},
  scrambleHL: {},
  scrambleSlotIndex: 0,
  scrambleDone: false,
  scrambleScore: 0,
  scrambleTotal: 0,
  scrambleWrongCount: 0,
  scrambleHintsUsed: 0,
};
