export const SYNTH_LESSONS = [
  {
    id: "shape",
    title: "Smooth, Pointed, Chunky, Spiky",
    summary: "Swap between smooth, pointed, chunky, and spiky wave shapes.",
    goal: "Listen for how the caterpillar's voice changes when the body shape changes.",
    prompt: "Press a note, then try each voice shape and pick the smoothest one.",
    successText: "You can make one smooth patch and one spiky patch.",
    visibleControls: ["oscType"],
  },
  {
    id: "brightness",
    title: "Dark Leaf, Bright Sun",
    summary: "Hear how a filter makes the caterpillar darker or brighter.",
    goal: "Use brightness to make the same note sound sleepy or shiny.",
    prompt: "Play a note, then slide Brightness until the sound feels much brighter than before.",
    successText: "You can make a dark sound and a bright sound from the same note.",
    visibleControls: ["cutoff"],
  },
  {
    id: "tail",
    title: "Tiny Tail, Long Trail",
    summary: "Short notes bounce. Long releases leave a glowing trail.",
    goal: "Hear how long the sound stays after the note is pressed.",
    prompt: "Make one note stop quickly, then make the next note float longer.",
    successText: "You can hear the difference between a short tail and a long trail.",
    visibleControls: ["release"],
  },
  {
    id: "snap",
    title: "Soft Bloom, Quick Bite",
    summary: "Sharp attacks bite fast. Soft attacks bloom more slowly.",
    goal: "Control how quickly the sound begins.",
    prompt: "Play the same note twice and make the second one start much more softly.",
    successText: "You can make a punchy note and a gentle note.",
    visibleControls: ["attack"],
  },
  {
    id: "ring",
    title: "Ring Or No Ring",
    summary: "Hear how the filter can whistle and glow around the note.",
    goal: "Use ring to make the sound round and calm or more resonant and zingy.",
    prompt: "Play a note, then raise Ring until you hear a stronger edge around the sound.",
    successText: "You can hear the difference between a plain sound and a ringing sound.",
    visibleControls: ["resonance"],
  },
  {
    id: "air",
    title: "Clean Sound, Windy Sound",
    summary: "Mix in a little airy noise to make the sound dusty, breezy, or whispery.",
    goal: "Hear the difference between a clean note and a fuzzy airy note.",
    prompt: "Play a note, then raise Air until the sound feels more windy than clean.",
    successText: "You can make one clean patch and one airy patch.",
    visibleControls: ["noiseMix"],
  },
  {
    id: "wiggle-depth",
    title: "Still Voice, Wiggly Voice",
    summary: "Add motion so the sound gently sways instead of staying perfectly still.",
    goal: "Use wiggle amount to make the sound calm or moving.",
    prompt: "Play a note, then raise Wiggle until the sound starts to sway.",
    successText: "You can hear the difference between a still sound and a wiggly sound.",
    visibleControls: ["lfoDepth"],
  },
  {
    id: "wiggle-speed",
    title: "Slow Wiggle, Fast Wiggle",
    summary: "Keep the wiggle, but change how quickly it moves.",
    goal: "Control whether the motion is slow and sleepy or quick and buzzy.",
    prompt: "Play a note, then try a slow wiggle and a fast wiggle.",
    successText: "You can hear the difference between slow motion and fast motion.",
    visibleControls: ["lfoRate"],
  },
];
